import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Movement from 'App/Models/Movement'

export default class MovementSeeder extends BaseSeeder {
  public async run () {
    await Movement.createMany([
      {
        "id": 1,
        "cod": "MXRF11",
        "date_operation": "25/10/2022",
        "qtd": 5,
        "type": 1,
        "type_operation": 1,
        "month_ref": 10,
        "year": 2022,
        "unity_value": 10.25,
        "obs": "",
        "fee": 0.02,
        "total": 51.27,
      },
      {
        "id": 2,
        "cod": "HGCR11",
        "date_operation": "25/10/2022",
        "qtd": 3,
        "type": 1,
        "type_operation": 1,
        "month_ref": 10,
        "year": 2022,
        "unity_value": 103.88,
        "obs": "",
        "fee": 0.14,
        "total": 311.78,
      },
      {
        "id": 3,
        "cod": "MXRF11",
        "date_operation": "25/11/2022",
        "qtd": 5,
        "type": 1,
        "type_operation": 2,
        "month_ref": 11,
        "year": 2022,
        "unity_value": 10.25,
        "obs": "",
        "fee": 0.02,
        "total": 51.27,
      },
      {
        "id": 4,
        "cod": "HGCR11",
        "date_operation": "25/10/2022",
        "qtd": 3,
        "type": 1,
        "type_operation": 2,
        "month_ref": 10,
        "year": 2022,
        "unity_value": 1.20,
        "obs": "",
        "fee": 0.14,
        "total": 3.60,
      },
      {
        "id": 5,
        "cod": "MXRF11",
        "date_operation": "25/11/2022",
        "qtd": 5,
        "type": 1,
        "type_operation": 2,
        "month_ref": 11,
        "year": 2022,
        "unity_value": 10.25,
        "obs": "",
        "fee": 0.02,
        "total": 51.27,
      },
      {
        "id": 6,
        "cod": "HGCR11",
        "date_operation": "25/10/2022",
        "qtd": 3,
        "type": 1,
        "type_operation": 3,
        "month_ref": 10,
        "year": 2022,
        "unity_value": 1.20,
        "obs": "",
        "fee": 0.14,
        "total": 3.74,
      },
      {
        "id": 7,
        "cod": "MXRF11",
        "date_operation": "17/10/2022",
        "qtd": 9,
        "type": 1,
        "type_operation": 3,
        "month_ref": 10,
        "year": 2022,
        "unity_value": 0.10,
        "obs": "",
        "fee": 0.00,
        "total": 0.90,
      },
      {
        "id": 9,
        "cod": "MXRF11",
        "date_operation": "15/11/2022",
        "qtd": 5,
        "type": 1,
        "type_operation": 1,
        "month_ref": 11,
        "year": 2022,
        "unity_value": 9.80,
        "obs": "",
        "fee": 0.08,
        "total": 49.08,
      },
      {
        "id": 10,
        "cod": "XPLG11",
        "date_operation": "15/11/2022",
        "qtd": 5,
        "type": 1,
        "type_operation": 1,
        "month_ref": 11,
        "year": 2022,
        "unity_value": 103.23,
        "obs": "",
        "fee": 0.26,
        "total": 516.41,
      },
      {
        "id": 14,
        "cod": "MXRF11",
        "date_operation": "15/10/2021",
        "qtd": 9,
        "type": 1,
        "type_operation": 3,
        "month_ref": 10,
        "year": 2021,
        "unity_value": 0.10,
        "obs": "",
        "fee": 0.00,
        "total": 0.90,
      },
      {
        "id": 15,
        "cod": "HGCR11",
        "date_operation": "15/10/2021",
        "qtd": 3,
        "type": 1,
        "type_operation": 3,
        "month_ref": 10,
        "year": 2021,
        "unity_value": 1.20,
        "obs": "",
        "fee": 0.00,
        "total": 3.60,
      },
      {
        "id": 17,
        "cod": "PETR4",
        "date_operation": "15/02/2022",
        "qtd": 5,
        "type": 2,
        "type_operation": 1,
        "month_ref": 2,
        "year": 2022,
        "unity_value": 33.00,
        "obs": "",
        "fee": 11.00,
        "total": 176.00,
      },
      {
        "id": 18,
        "cod": "RDB",
        "date_operation": "15/01/2022",
        "qtd": 1,
        "type": 3,
        "type_operation": 1,
        "month_ref": 1,
        "year": 2022,
        "unity_value": 25000.00,
        "obs": "",
        "fee": 0.00,
        "total": 25000.00,
      }
    ])
  }
}
