version: "3.8"

services:
  accio_invest:
    container_name: accio_invest
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      # Uncomment the below line if you developing on MacOS
      #- /home/node/app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
    depends_on:
      - adonis-mysql
  adonis-mysql:
    image: mysql
    container_name: adonis-mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: deverick
      MYSQL_PASSWORD: 8294
      MYSQL_DATABASE: accio
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "7300:80"
