version: "3.8"

services:
  accio_invest:
    container_name: accio_invest
    restart: always
    networks:
      - mysql_host
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve
